export const projects = [
  {
    title: 'E-Commerce',
    description:"Modelo de uma loja online, com pagamento usando cartão de credito.",
    image: '/images/ecommerce.png',
    tags: ['NextJS', 'JavaScript'],
    visit: 'https://eyesgreen-store.vercel.app',
    id: 0,
  },
  {
    title: 'Comunidade',
    description: "Aplicação web, para comunidade, onde os usuários podem criar salas de assuntos e tópicos variados para discutir.",
      image: '/images/retro.png',
      tags: ['React', 'Firebase'],
    visit: 'https://amor-retrolovers.web.app',
    id: 1,
  },
  {
    title: 'Studio Tattoo',
    description: "Modelo de landing page, para studio de tattoo.",
      image: '/images/PC.png',
      tags: ['React', 'Tailwindcss', 'Google-Maps', 'EmailJS'],
    visit: 'https://studioinkzone.netlify.app',
    id: 2,
  },
  {
    title: 'Landing Page',
    description: "Uma landing page, com as informações e historia de uma empresa fictícia.",
    image: '/images/tftech.png',
    tags: ['HMTL5', 'CSS3'],
    visit: 'https://tftech.netlify.app',
    id: 3,
  },
  {
    title: 'Gym Fitness',
    description: "Landing page, para academia.",
    image: '/images/academia.png',
    tags: ['HMTL5', 'CSS3', 'ReactJS'],
    visit: 'https://gymfitnessplus.netlify.app/',
    id: 4,
  },
  {
    title: 'Dra Mary Page',
    description: "Landing Page para Clinica Odontologica.",
    image: '/images/dramaryjane.png',
    tags: ['HMTL5', 'CSS3', 'ReactJS', 'Styled-components'],
    visit: 'https://dramaryjane.netlify.app/',
    id: 5,
  },
  {
    title: 'YourHouse',
    description: "Aplicação para venda e aluguem de imoveis.",
    image: '/images/yourhouse.png',
    tags: ['ReactJS', 'TailwindCss', 'Firebase', 'Leaft-Maps'],
    visit: 'https://houseyour.netlify.app/',
    id: 6,
  },
  {
    title: 'Photographer Portfolio',
    description: "Portifolio para Fotografos.",
    image: '/images/photographer.png',
    tags: ['HMTL5', 'CSS3', 'ReactJS'],
    visit: 'https://photographer-sofia.netlify.app/',
    id: 7,
  },
  {
    title: 'Escritorio de Advocacia Moderno',
    description: "Landing Page para Escritorio de Advocacia.",
    image: '/images/advogacia.png',
    tags: ['HMTL5', 'CSS3', 'ReactJS', 'Taildwindcss'],
    visit: 'https://advogaciamoderna.netlify.app/',
    id: 8,
  },
  {
    title: 'CallService',
    description: "Plataforma para gestão de chamada de serviço.",
    image: '/images/callservice.png',
    tags: ['ReactJS', 'Styled-components', 'Firebase'],
    visit: 'https://callservice.netlify.app/',
    id: 9,
  },
  {
    title: 'Barber',
    description: "SPA, para barbearias.",
    image: '/images/barber.png',
    tags: ['ReactJS', 'Styled-components', 'EmailJS'],
    visit: 'https://barbeariashop.netlify.app',
    id: 10,
  },
  {
    title: 'Personal Finance',
    description: "Aplicação para controlar financia pessoal.",
    image: '/images/personalfinance.png',
    tags: ['ReactJS', 'Tailwindcss', 'Firebase'],
    visit: 'https://finance-personal.netlify.app',
    id: 10,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Iniciei com os estudos da programação', },
  { year: 2022, text: 'Trabalhando como freelancer', },
  { year: 2023, text: 'Trabalhando como freelancer', },
];
